#!/bin/bash

apue_include_path='/home/'$USER'.../apue3/include/'
apue_lib_path='/home/'$USER'/.../apue3/lib/'

output_name=$(echo $1 | awk -F . '{print $1}')
echo $apue_include_path
echo $apue_lib_path
echo $output_name

#gcc -o "$output_name" $1 -I "$apue_include_path" -L "$apue_lib_path" -lapue

# -I tells gcc which directory to look for the include file 
# -L tells it the location of the library directory
# -lapue, tells the name of the library file to look for in that directory
# Such that -LXXX means to look for a file in the library directory with the name: libXXX.a or libXXX.so.
